# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Setup Spigot

on:
   workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
   workflow_call:
    inputs:
      version:
        required: false
        type: string
      path:   
        required: false
        type: string
jobs:
  setup-java:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/setup-java@v3
       with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
  setup-spigot:
     runs-on: ubuntu-latest
     steps:
      - name: Download Spigot Server ${{inputs.version}}
        run: curl https://download.getbukkit.org/spigot/spigot-${{inputs.version}}.jar -o server/spigot.jar
  run-spigot: 
     needs: [setup-java, setup-spigot]
     runs-on: ubuntu-latest
     steps:
      - name: Run server
        run: java server/spigot.jar
 
