name: spigot tests with docker
on:
   workflow_dispatch:
    inputs:
      version:
        required: true
        type: number
        default: 1.19 #test 
jobs:
  spigot-docker:
    runs-on: ubuntu-latest
    container:
      image: nimmis/spigot
      env:
        EULA: true
        SPIGOT_VER: ${{inputs.version}}
      ports:
        - 80
    steps:
      - name: download java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: download python
      - uses: actions/setup-python@v4
        with:
         python-version: '3.9'   
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)     
      - name: Run Server
        run:  mc_start
