name: spigot tests with docker
on:
   workflow_dispatch:
    inputs:
      version:
        required: true
        type: number
        default: 1.19  
jobs:
  spigot-docker:
    runs-on: ubuntu-latest
    container:
      image: nimmis/spigot
      env:
        EULA: true
        SPIGOT_VER: ${{inputs.version}}
      ports:
        - 80
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)     
